package com.example.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller //Controller class
@RequestMapping(path="/api")
public class MainController {
    @Autowired //Get bean called userRepository, auto generated by spring
    private UserRepository userRepository;

    @PostMapping(path="/add") //Only POST requests
    public @ResponseBody String addNewUser (@RequestParam String FirstName, @RequestParam String LastName, @RequestParam String Email, @RequestParam String Password){
        //ResponseBody means returned string is response
        //RequestParam means its parameter from GET/POST request
        DrinkEetUser user = new DrinkEetUser();
        user.setFirstName(FirstName);
        user.setLastName(LastName);
        user.setEmail(Email);
        user.setPassword(Password);
        userRepository.save(user);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<DrinkEetUser> getAllUsers() {
        //Return JSON or XML with all users
        return userRepository.findAll();
    }
}
